### ISSUE TITLE
Generating addresses for Polkadot outside of the ledger.

### ISSUE THREAD

**Issue by remzrn** [Zondax/ledger-polkadot#23] opened 2020-09-28 16:58 UTC
Hello!

BIP 44 defines how addresses should be derived. But the current workflow documented for Polkadot [here](https://wiki.polkadot.network/docs/en/learn-ledger) is very evasive about the account type and address index meaning. 
I would like to reproduce the addresses generated by the ledger outside, for instance with [Subkey](https://www.substrate.io/kb/integrate/subkey). I would expect that something like `mnemonic//44//354//0/0` would reproduce the ledger address obtained with setting both the account type and address index to 0 for instance, but it does not seem to be the case. I tried to mix different soft/hard paths, or to add a coin change placeholder to the path, but it did not help.
Could we get the formula that translates a ledger derivation choice to a subkey formatted command?
Thanks a lot.

**Comment by jleni** [comment] 2020-09-28 17:07
This is explained here:
https://github.com/Zondax/ledger-polkadot/issues/21

The problem is not much about the derivation but in the way the mnemonic it handled

**Comment by jleni** [comment] 2020-09-28 17:09
I have pinned issue #21 as I believe many people may have the same question. 
We can move the discussion there.
Closing as duplicate

**Closed by jleni** 2020-09-28 17:09 UTC
